version: '3.8'

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: database:latest
    container_name: puhelinluettelo_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  backend:
    build:
      context: ./puhelinluettelo-backend
      dockerfile: Dockerfile
    container_name: puhelinluettelo_backend
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/mydatabase
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - mynetwork

  frontend:
    build:
      context: ./puhelinluettelo-frontend
      dockerfile: Dockerfile
    container_name: puhelinluettelo_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
