version: '3.8'

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: database:latest
    container_name: puhelinluettelo_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge