# https://www.playframework.com/documentation/latest/Configuration
# play.modules.enabled += "play.api.db.slick.evolutions.SlickEvolutionsModule"
# play.modules.enabled += "play.api.db.slick.DbModule"

slick.dbs.default.profile = "slick.jdbc.PostgresProfile$"
slick.dbs.default.db.driver = "org.postgresql.Driver"
slick.dbs.default.db.url="jdbc:postgresql://localhost:5433/mydatabase"
slick.dbs.default.db.user="myuser"
slick.dbs.default.db.password="mypassword"
# Allow CORS
play.filters.enabled += "play.filters.cors.CORSFilter"
play.filters.cors {
  allowedOrigins = null
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE"]
  allowedHttpHeaders = ["Accept", "Content-Type"]
  allowCredentials = true
}
